services:

  postgres1:
    image: postgres:16
    container_name: postgres1
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
     - ./pgdata1:/var/lib/postgresql/data
    networks:
      - db

  postgres2:
    image: postgres:16
    container_name: postgres2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
     - ./pgdata2:/var/lib/postgresql/data
    networks:
      - db


networks:
  db:
    driver: bridge
